Repository spryker-sdk/composer-constrainer, pull requests merged in 2021-09, with the labels that each got.

#18 Move test files into tests/ dir
  .gitignore
  codeception.yml
  composer.json
  phpstan.neon
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerLock/ComposerLockReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Finder/UsedForeignModuleFinder/UsedForeignModuleFinder.php
  tests/SprykerSdkTest/Zed/ComposerConstrainer/codeception.yml
  tests/app/src/.gitkeep
  tests/bootstrap.php
  tests/config/Shared/stores.php
Labels: merge-only, prio

#17 Improve composer.json generation. Add tests.
  .github/workflows/ci.yml
  .gitignore
  codeception.yml
  composer.json
  dependency.json
  phpstan.neon
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonWriter.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerLock/ComposerLockReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Finder/UsedForeignModuleFinder/UsedForeignModuleFinder.php
  tests/SprykerSdkTest/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonWriterTest.php
  tests/SprykerSdkTest/Zed/ComposerConstrainer/codeception.yml
  tests/_files/composer2space.json
  tests/_files/composer4space.json
  tests/app/src/.gitkeep
  tests/bootstrap.php
  tests/config/Shared/stores.php
Labels: bug, ready-for-release, merge-only

#14 AA-190 Composer constrainer strict mode
  composer.json
  dependency.json
  phpstan.json
  phpstan.neon
  src/SprykerSdk/Shared/ComposerConstrainer/Transfer/composer_constrainer.transfer.xml
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerJson/ComposerJsonReaderInterface.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerLock/ComposerLockReader.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Composer/ComposerLock/ComposerLockReaderInterface.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/ComposerConstrainerBusinessFactory.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/ComposerConstrainerFacade.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/ComposerConstrainerFacadeInterface.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Finder/StrictFinder.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/SprykerReflector/SprykerClassReflector.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/SprykerReflector/SprykerReflectionHelper.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/SprykerReflector/SprykerXmlReflector.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/SprykerReflector/SprykerYamlReflector.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Updater/StrictConstraintUpdater.php
  src/SprykerSdk/Zed/ComposerConstrainer/Business/Validator/StrictConstraintValidator.php
  src/SprykerSdk/Zed/ComposerConstrainer/Communication/Console/ComposerConstraintConsole.php
  src/SprykerSdk/Zed/ComposerConstrainer/ComposerConstrainerConfig.php
Labels: improvement, ready-for-release
